name: Cypress tests

on: push
  # pull_request:
  #   branches:
  #     - main

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/login.cy.js
      
      - name: Subindo relatório
        if: always() # Certifique-se de que o relatório será salvo mesmo se os testes falharem
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report # Nome do artifact
          path: mochawesome-report # Caminho onde o relatório está salvo
          retention-days: 3 # Define que o artifact expira em 3 dias